



### GET Home
GET http://localhost:4000/studHome/
Content-Type: application/json



###POST
POST http://localhost:4000/Feedback/
Content-Type: application/json

{
    "subjectCode" : "HS8251"
}

### GET
GET http://localhost:3000//FeedbackGetStaffInfo/
Content-Type: application/json